// app/layout.js or app/layout.tsx

import "./globals.css";
import Header from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { Prata } from "next/font/google";

// Correct usage of Prata font
const prata = Prata({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Apply Prata font using className */}
      <body className={`${prata.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
